project:
  type: website

website:
  title: "CMSC 1217 : Introduction to Data Analytics"

  navbar:
    left:
      - href: index.qmd
        text: Home      

  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Course information"
        contents:
          - href: course/syllabus.qmd
            text: Syllabus
          - href: course/schedule.qmd
            text: Schedule
          - href: shared/policies/office-hours.qmd
            text: Office Hours
          - href: shared/policies/homework-coursework.qmd
            text: Assignment Policies
          - href: shared/policies/general-policies.qmd
            text: General Policies


      - section: "Weekly Overview"
        contents:
          - href: weekly-overview/week-01/
            text: Week 1
          #- href: weekly-overview/week-02/
            #text: Week 2

      - section: "Weekly Assignments"
        contents:
          - href: assignments/week-01-assignments/
            text: Week 1
           
      
      
      - section: "Guides"
        contents:
          - href: shared/guides/setup/miniconda.qmd
            text: Miniconda Setup


format:
  html:
    toc: false
    theme: cosmo
    css:
      - shared/assets/course.css
      - styles.css




