project:
  type: website

website:
  title: "CMSC 1217 : Introduction to Data Analytics"

  navbar:
    left:
      - href: index.qmd
        text: Home      

  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Course information"
        contents:
          - href: course/syllabus.qmd
            text: Syllabus
          - href: course/schedule.qmd
            text: Schedule
          - href: shared/policies/office-hours.qmd
            text: Office Hours
          - href: shared/policies/homework-coursework.qmd
            text: Assignment Policies
          - href: shared/policies/general-policies.qmd
            text: General Policies


      - section: "Weekly Overview"
        contents:
          - href: weeks/week-01/week-01.qmd
            text: Week 1
          #- href: weeks/week-02.qmd
            #text: Week 2

      - section: "Weekly Assignments"
        contents:
          - href: assignments/week-01.qmd
            text: Week 1
           
      
      
      - section: "Guides"
        contents:
          - href: guides/week-01/environment-setup-guide-miniconda.qmd
            text: Miniconda Setup

format:
  html:
    toc: false
    theme: cosmo
    css: styles.css



